import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { withDatabase } from './shared.js';
import { importCsv } from '../import/importer.js';
const args = process.argv.slice(2);
if (args.some(arg => arg.startsWith('--') && arg !== '--replace-catalog') || args.filter(arg => !arg.startsWith('--')).length > 1) throw new Error('Использование: db:import [путь.csv] [--replace-catalog]');
const customFile = args.find(arg => !arg.startsWith('--'));
const file = customFile ? resolve(customFile) : fileURLToPath(new URL('../../../../olimpiady.csv', import.meta.url));
const buffer = await readFile(file);
const report = await withDatabase(db => importCsv(db, buffer, file, { replaceCatalog: !customFile || args.includes('--replace-catalog') }));
await writeFile(new URL('../../../../data/import-report.json', import.meta.url), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report, null, 2));
